// @generated by Cratis. Source: CratisApp.Expenses.Approval.RejectExpense.RejectExpense. Time: 2026-09-05T16:10:45.9479100Z. Hash: 8D0FAE0C8FED183473EB248803C2C6EA11C91CC29CF8EDFAA84874BB362F6AB3
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRejectExpense {
    expenseId?: Guid;
    rejectedBy?: string;
}


export class RejectExpense extends Command<IRejectExpense, string> implements IRejectExpense {
    readonly route: string = '/api/expenses/approval/reject-expense';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('expenseId', Guid, false),
        new PropertyDescriptor('rejectedBy', String, false),
    ];

    private _expenseId!: Guid;
    private _rejectedBy!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get expenseId(): Guid {
        return this._expenseId;
    }

    set expenseId(value: Guid) {
        this._expenseId = value;
        this.propertyChanged('expenseId');
    }
    get rejectedBy(): string {
        return this._rejectedBy;
    }

    set rejectedBy(value: string) {
        this._rejectedBy = value;
        this.propertyChanged('rejectedBy');
    }

    static use(initialValues?: IRejectExpense): [RejectExpense, SetCommandValues<IRejectExpense>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RejectExpense, IRejectExpense>(RejectExpense, initialValues);
    }
}
