// @generated by Cratis. Source: CratisApp.Expenses.Approval.ApproveExpense.ApproveExpense. Time: 2026-09-05T16:36:35.4941554Z. Hash: 5D4943698665B205591885F1463C81481EAB20620BD890DBFBB0E3A107072099
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IApproveExpense {
    approvedBy?: string;
    expenseId?: Guid;
    reason?: string;
}


export class ApproveExpense extends Command<IApproveExpense, string> implements IApproveExpense {
    readonly route: string = '/api/expenses/approval/approve-expense';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('approvedBy', String, false),
        new PropertyDescriptor('expenseId', Guid, false),
        new PropertyDescriptor('reason', String, false),
    ];

    private _approvedBy!: string;
    private _expenseId!: Guid;
    private _reason!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get approvedBy(): string {
        return this._approvedBy;
    }

    set approvedBy(value: string) {
        this._approvedBy = value;
        this.propertyChanged('approvedBy');
    }
    get expenseId(): Guid {
        return this._expenseId;
    }

    set expenseId(value: Guid) {
        this._expenseId = value;
        this.propertyChanged('expenseId');
    }
    get reason(): string {
        return this._reason;
    }

    set reason(value: string) {
        this._reason = value;
        this.propertyChanged('reason');
    }

    static use(initialValues?: IApproveExpense): [ApproveExpense, SetCommandValues<IApproveExpense>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ApproveExpense, IApproveExpense>(ApproveExpense, initialValues);
    }
}
