// @generated by Cratis. Source: CratisApp.Expenses.Approval.SubmitExpense.SubmitExpense. Time: 2026-09-05T16:10:45.9479100Z. Hash: B83767A861A6AAD2EEF5211CA0BEF69D233B6017016FC725178282146829D2CD
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface ISubmitExpense {
    amount?: number;
    description?: string;
}

export class SubmitExpenseValidator extends CommandValidator<ISubmitExpense> {
    constructor() {
        super();
        this.ruleFor(c => c.amount).greaterThan(0).withMessage('Amount must be greater than zero');
        this.ruleFor(c => c.description).notEmpty().withMessage('Description is required');
    }
}

export class SubmitExpense extends Command<ISubmitExpense, Guid> implements ISubmitExpense {
    readonly route: string = '/api/expenses/approval/submit-expense';
    readonly validation: CommandValidator = new SubmitExpenseValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('amount', Number, false),
        new PropertyDescriptor('description', String, false),
    ];

    private _amount!: number;
    private _description!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get amount(): number {
        return this._amount;
    }

    set amount(value: number) {
        this._amount = value;
        this.propertyChanged('amount');
    }
    get description(): string {
        return this._description;
    }

    set description(value: string) {
        this._description = value;
        this.propertyChanged('description');
    }

    static use(initialValues?: ISubmitExpense): [SubmitExpense, SetCommandValues<ISubmitExpense>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SubmitExpense, ISubmitExpense>(SubmitExpense, initialValues);
    }
}
